export const commonConstances = {
    TOGGLE_LOGIN_MODAL: "TOGGLE_LOGIN_MODAL",
    TOGGLE_SIGNIN_MODAL: "TOGGLE_SIGNIN_MODAL",
    TOGGLE_CART_ITEM_MODAL: "TOGGLE_CART_ITEM_MODAL",
    TOGGLE_PAYMENT_METHOD: "TOGGLE_PAYMENT_METHOD",
    UPDATE_ITEM_QUANTITY: "UPDATE_ITEM_QUANTITY",
    UPDATE_CART_ITEM: "UPDATE_CART_ITEM",
    SELECT_PRODUCT: "SELECT_PRODUCT",
    ADD_CART_ITEM: "ADD_CART_ITEM",
    DISCARD_ITEM: "DISCARD_ITEM",
    LOGIN_BEGIN: "LOGIN_BEGIN",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOG_OUT: "LOG_OUT"
}